const kurlyDB = [
    {
        src:'./images/kurly_001.jpg',
        name:'[해태] 여름 시즌 한정 트로피컬 에디션 간식 4종 (택1)',
        summary:'새콤달콤한 여름맛 간식',
        price:3580,
        sale:7,
        review:154,
    },
    {
        src:'./images/kurly_002.jpg',
        name:'[피자로빈슨] 뉴욕 메가 슬라이스 피자 페퍼로니',
        summary:'짭쪼름한 페퍼로니가 듬뿍',
        price:5500,
        sale:20,
        review:18,
    },
    {
        src:'./images/kurly_003.jpg',
        name:'[몽쉘] 크림 브라우니 샌드위치 케이크',
        summary:'부드러운 크림과 진한 브라우니의 조화',
        price:4980,
        sale:10,
        review:89,
    },
    {
        src:'./images/kurly_004.jpg',
        name:'[풀무원] 생가득 얇은피 꽉찬속 만두 1kg',
        summary:'얇은 피에 꽉 찬 속으로 만두의 끝판왕',
        price:9800,
        sale:15,
        review:312,
    },
    {
        src:'./images/kurly_005.jpg',
        name:'[오리온] 꼬북칩 초코츄러스맛',
        summary:'바삭바삭 4겹 식감에 달콤한 초코 맛',
        price:3280,
        sale:5,
        review:456,
    },
    {
        src:'./images/kurly_006.jpg',
        name:'[빙그레] 메로나 아이스크림 바(8개입)',
        summary:'여름철 필수템, 멜론 맛 아이스크림',
        price:7980,
        sale:12,
        review:132,
    },
    {
        src:'./images/kurly_007.jpg',
        name:'[CJ] 비비고 왕교자 1.05kg',
        summary:'든든한 한끼 교자 만두',
        price:10980,
        sale:18,
        review:524,
    },
    {
        src:'./images/kurly_008.jpg',
        name:'[매일] 바리스타룰스 아메리카노 325ml',
        summary:'깔끔한 맛의 스페셜티 커피',
        price:1800,
        sale:8,
        review:74,
    },
    {
        src:'./images/kurly_009.jpg',
        name:'[스팸] 클래식 200g x3캔',
        summary:'언제나 맛있는 스팸 클래식',
        price:9800,
        sale:22,
        review:201,
    },
    {
        src:'./images/kurly_010.jpg',
        name:'[롯데] 꼬깔콘 고소한맛 대용량',
        summary:'한입 먹으면 멈출 수 없는 고소함',
        price:2980,
        sale:6,
        review:391,
    },
    {
        src:'./images/kurly_011.jpg',
        name:'[노브랜드] 감자칩 오리지널 110g',
        summary:'바삭하고 담백한 감자칩의 정석',
        price:1580,
        sale:9,
        review:264,
    },
    {
        src:'./images/kurly_012.jpg',
        name:'[서울우유] 초코우유 300ml',
        summary:'진한 초콜릿 풍미 가득한 우유',
        price:1900,
        sale:5,
        review:83,
    },
];
